settings:
  title: 'vaaski.dev service status'
  url: 'https://status.vaaski.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Epicly Working'
  notAllmonitorsOperational: 'Some Systems Fucked'
  monitorLabelOperational: 'Not Fucked'
  monitorLabelNotOperational: 'Fucked'
  monitorLabelNoData: 'idk'
  dayInHistogramNoData: 'idk'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' fuckup(s)' # xx incident(s) recorded

monitors:
  - id: jellyfin
    name: Jellyfin
    description: "The Free Software Media System"
    url: "https://jelly.vaaski.dev/web/index.html"

  - id: jellyseerr
    name: Jellyseerr
    description: "fork of overseerr for jellyfin support"
    url: "https://seerr.vaaski.dev/login"

  - id: hetzner
    name: Hetzner VPS
    url: "https://hetzner.vaaski.dev"
    linkable: false

  - id: hserver
    name: Static File Server
    url: "https://home.vaaski.dev/static/"

  - id: send
    name: FF Send
    description: "📬 Simple, private file sharing."
    url: "https://send.vaaski.dev"

  - id: mail
    name: Email Server
    url: "https://mail.vaaski.dev"
    linkable: false

  - id: resync
    name: resync
    url: "https://hetzner.vaaski.dev/resync/?EIO=4&transport=polling"

  - id: transmission
    name: Transmission WebUI
    url: "https://transmission.vaaski.dev"
    expectStatus: 401

  - id: jdownloader
    name: JDownloader 2 WebUI
    url: "https://jdownloader.vaaski.dev"
    expectStatus: 401

  - id: radarr
    name: Radarr
    url: "https://radarr.vaaski.dev"
    expectStatus: 401

  - id: sonarr
    name: Sonarr
    url: "https://sonarr.vaaski.dev"
    expectStatus: 401

  - id: prowlarr
    name: Prowlarr
    url: "https://prowlarr.vaaski.dev"
    expectStatus: 401

  - id: fuckmoodle
    name: Fuckmoodle Backend
    url: "https://pissfried.shr.li/fuckmoodle/?EIO=4&transport=polling"
    expectStatus: 302

