settings:
  title: 'Status Page'
  url: 'https://status.vaaski.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Epicly Working'
  notAllmonitorsOperational: 'Some Systems Fucked'
  monitorLabelOperational: 'Not Fucked'
  monitorLabelNotOperational: 'Fucked'
  monitorLabelNoData: 'idk'
  dayInHistogramNoData: 'idk'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' fuckup(s)' # xx incident(s) recorded

monitors:
  - id: jellyfin
    name: Jellyfin
    description: "The Free Software Media System"
    url: "https://jelly.vaaski.dev/web/index.html"
    method: GET
    expectStatus: 200
    linkable: true

  - id: hetzner
    name: Hetzner VPS
    description: "Hetzner VPS"
    url: "https://hetzner.vaaski.dev"
    method: GET
    expectStatus: 200
    linkable: false

  - id: hserver
    name: Static Home File Server
    description: "Static Home File Server"
    url: "https://home.vaaski.dev/static/"
    method: GET
    expectStatus: 200
    linkable: true

  - id: send
    name: Mozilla Send
    description: "📬 Simple, private file sharing."
    url: "https://send.vaaski.dev"
    method: GET
    expectStatus: 200
    linkable: true

  - id: mail
    name: Email Server
    description: "Email Server"
    url: "https://mail.vaaski.dev"
    method: GET
    expectStatus: 200
    linkable: false

  - id: resync
    name: Resync Backend
    description: "Resync Backend"
    url: "https://hetzner.vaaski.dev/resync/?EIO=4&transport=polling"
    method: GET
    expectStatus: 200

  - id: fuckmoodle
    name: Fuckmoodle Backend
    description: "Fuckmoodle backend"
    url: "https://pissfried.shr.li"
    method: GET
    expectStatus: 302

